version: '3.8'

services:
  app:
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "4", "--timeout", "120", "app:app"]
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  db:
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  web:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Remove phpMyAdmin in production for security
  phpmyadmin:
    profiles:
      - production-disabled 