version: '3.8'

services:
  app:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./app:/app
      - ./logs:/app/logs
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]
    ports:
      - "5000:5000"  # Expose Flask development server directly

  web:
    ports:
      - "8080:80"
      - "8443:443"  # Additional port for SSL if needed

  phpmyadmin:
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db 